# Generated by Django 2.1.5 on 2021-08-29 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_page_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 29, 13, 34, 15, 82086, tzinfo=utc)),
        ),
    ]
