# Generated by Django 2.1.5 on 2021-08-29 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210829_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 29, 14, 44, 11, 667546, tzinfo=utc)),
        ),
    ]
