# Generated by Django 2.1.5 on 2021-08-30 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20210830_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 9, 33, 36, 915061, tzinfo=utc)),
        ),
    ]
